services:
  - type: web
    name: zaddys-api
    runtime: python
    rootDir: zaddys-backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn core.wsgi:application
    healthCheckPath: /api/products/
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
