# Generated by Django 6.1 on 2026-08-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_productoption_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='product-options/'),
        ),
    ]
